@startuml
'https://plantuml.com/class-diagram
package model {
abstract class SimulationObject{

}

class SimulationAgent {

}

interface Agent {
    +setRule(Rule rule)
    +update()
}

interface Runnable {
    +run()
}

interface Observer {
    +hasChanged(Value value)
}

package behaviour {
    abstract Rule {
        +act()
    }
    package composites {
    }
    package leafs {
    }

}

class Board {

}

class Simulation {
    +step()
    +addObject(SimulationObject object)
    +getObjects()
    +getBoard()
}



SimulationObject <|-right- SimulationAgent

Runnable <|-up- SimulationAgent
Agent <|-up- SimulationAgent
Observer <|-up- SimulationAgent


Board <-right- SimulationObject
SimulationObject <-- Board

behaviour <-- Agent

Rule <|-- composites
Rule <|-- leafs

Simulation -up-> SimulationObject
Simulation -up-> Board
Simulation --> Agent
}





@enduml